#!/bin/env bash

filename=$(basename $1 .pgf)

# make latex file
touch "${filename}_temp.tex"
echo "\documentclass{standalone}" >> "${filename}_temp.tex"
echo "\usepackage[sfdefault, light]{inter}" >> "${filename}_temp.tex"
echo "\usepackage{pgf}" >> "${filename}_temp.tex"
echo "\DeclareMathSizes{10}{11}{9}{9}" >> "${filename}_temp.tex"
echo "\begin{document}" >> "${filename}_temp.tex"
echo "\input{${filename}.pgf}" >> "${filename}_temp.tex"
echo "\end{document}" >> "${filename}_temp.tex"

# run latex to get pdf
latexmk -quiet -pdf "${filename}_temp.tex"

# convert pdf to svg
pdf2svg "${filename}_temp.pdf" "${filename}_temp.svg"

# compress svg
svgcleaner "${filename}_temp.svg" "${filename}.svg"

# clean up
rm "${filename}_temp.tex"
rm "${filename}_temp.pdf"
rm "${filename}_temp.svg"
texclean
